SERVICE_RUN_SCRIPT_NAME_${PN}   ?= "run"
SERVICE_RUN_SCRIPT_TARGET       ?= "run"
SERVICE_LOG_SCRIPT_NAME_${PN}   ?= "log"
SERVICE_LOG_SCRIPT_TARGET       ?= "log/run"

MULTILOG_TOOL = "${bindir}/s6-log"
SVC_STATUS_CMD = "${bindir}/s6-svok"
SVC_START_CMD = "${bindir}/s6-svc -u"
SVC_ONCE_CMD = "${bindir}/s6-svc -o"
SVC_STOP_CMD = "${bindir}/s6-svc -d"
SVC_KILL_CMD = "${bindir}/s6-svc -k"
SVC_RESTART_CMD = "${bindir}/s6-svc -r"
SVC_RELOAD_CMD = "${bindir}/s6-svc -h"
